
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow
  template:
    metadata:
      labels:
        app: airflow
    spec:
      containers:
        - name: airflow
          image: puckel/docker-airflow:latest
          ports:
            - containerPort: 8080
          env:
            - name: LOAD_EX
              value: "n"
            - name: EXECUTOR
              value: LocalExecutor
            - name: POSTGRES_HOST
              value: "your-postgres-host"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              value: "your-username"
            - name: POSTGRES_PASSWORD
              value: "your-password"
            - name: POSTGRES_DB
              value: "your-dbname"
          volumeMounts:
            - name: airflow-dags
              mountPath: /usr/local/airflow/dags
            - name: airflow-logs
              mountPath: /usr/local/airflow/logs
            - name: airflow-plugins
              mountPath: /usr/local/airflow/plugins
      volumes:
        - name: airflow-dags
          persistentVolumeClaim:
            claimName: airflow-dags-pvc
        - name: airflow-logs
          persistentVolumeClaim:
            claimName: airflow-logs-pvc
        - name: airflow-plugins
          persistentVolumeClaim:
            claimName: airflow-plugins-pvc
