version: "3.8"

services:
  superset_db:
    image: postgres:13
    environment:
      POSTGRES_DB: superset
      POSTGRES_USER: superset
      POSTGRES_PASSWORD: superset
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - superset_network

  superset_cache:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - superset_network

  superset:
    image: apache/superset:latest
    depends_on:
      - superset_db
      - superset_cache
    environment:
      SUPERSET_CONFIG_PATH: /app/pythonpath/superset_config.py
    volumes:
      - ./superset_config.py:/app/pythonpath/superset_config.py
    ports:
      - "8088:8088"
    networks:
      - superset_network
    command: >
      sh -c '
      superset db upgrade &&
      superset init &&
      superset fab create-admin --username admin --firstname Superset --lastname Admin --email admin@superset.com --password admin'
      
networks:
  superset_network:
    driver: bridge

